Feat: Handle UpdateStreamingPaymentMetadata mutation
JoinColony/colonyCDappAuthProxy pull request #19
Opened 2024-06-12 14:17 UTC by iamsamgibbs

[See CDapp counterpart](https://github.com/JoinColony/colonyCDapp/pull/2338)

This PR handles the UpdateStreamingPaymentMetadata mutation

2024-06-13 16:31 UTC, rdig requested changes
Tested as part of JoinColony/colonyCDapp/pull/2338 plus looked at the code which is all what I expected from this change

I'm only rejecting this because I can't recreate the test scenario

2024-06-13 16:31 UTC, rdig commented on src/routes/graphql/mutations.ts
> +            });
I can't say for sure, but I know at least this much that this will slow down this query (the one the CDapp makes to the Auth Proxy) quite considerable.

And in a production setting this most likely will cause timeouts, which will result in the user not being able to make this update.

We might need to refactor this into a Lambda, if that starts happening

2024-06-13 16:51 UTC, iamsamgibbs commented on src/routes/graphql/mutations.ts
> +            });
Ah, that makes sense, I hadn't considered that. I can move it into a lambda now if you (or @jakubcolony ) would prefer, otherwise can leave it and address it at a later point if it becomes an issue.

2024-06-20 18:18 UTC, jakubcolony reviewed
Just leaving a comment for now

2024-06-21 12:04 UTC, iamsamgibbs commented on src/routes/graphql/mutations.ts
> +            });
My only other thought was that we could call `editColonyByDelta` with the endCondition and limitAmount as parameters with the rest of the multicall and handle it on the block-ingestor instead.

2024-07-09 14:51 UTC, rdig commented on src/routes/graphql/mutations.ts
> +            });
> Leaving implementation details aside, I think this is the most correct way of validating whether user should be allowed to update the metadata

By "this" do you mean sticking it inside a lambda ?

2024-07-10 18:41 UTC, jakubcolony commented on src/routes/graphql/mutations.ts
> +            });
@rdig whether it's done in lambda/auth proxy is an implementation detail (in my eyes), I just meant the check that gets all the user roles to determine if user holds certain permissions is the correct way. 

Shall we go with this implementation and refactor if necessary?

2024-07-10 18:42 UTC, jakubcolony approved these changes
As long as @rdig is okay with keeping it in the auth proxy, this looks good to me 👍

2024-07-12 10:29 UTC, rdig approved these changes

2024-07-12 13:40 UTC, davecreaser approved these changes

2024-07-15 20:12 UTC, rdig commented
Since JoinColony/colonyCDapp#2338 got merged, this can be as well, right ?

2024-07-16 07:16 UTC, iamsamgibbs commented
> Since [JoinColony/colonyCDapp#2338](https://github.com/JoinColony/colonyCDapp/pull/2338) got merged, this can be as well, right ?

I thought I'd leave it for now as there is no streaming payments feature branch - but I've also just realised there are already references to streaming payments on master, so I'll merge this in now. 👍

2024-07-16 07:17 UTC, merged