Check transaction creator on update
JoinColony/colonyCDappAuthProxy pull request #23
Opened 2024-07-23 15:03 UTC by davecreaser

When making a mutation to update a transaction, this should only pass the auth proxy if the "from" parameter in the request is not only the same as the currently logged in user, but also the same as the "from" parameter of the actual transaction in the database.

See CDapp counterpart for proper testing steps.

2024-07-23 15:06 UTC, davecreaser commented on src/routes/graphql/graphql.ts
> +          }`
This is the only `real` change in this file, the rest is all linters, sorry 🙃 

What I'm doing here is just making it a bit easier to see in the logs when a request has passed/failed auth.

2024-07-23 15:06 UTC, davecreaser commented on src/routes/graphql/mutations.ts
> +      }
This is the only `real` change in this file, the rest is linters again!

2024-07-23 22:09 UTC, rdig requested changes
Changes work as tested in JoinColony/colonyCDapp#2758 but please revert the style changes. 

So the quotes style we use generally in projects is single quotes, meaning most of your changes need to be reverted.

A proper fix for them is to put actual eslint rules to enforce this, but I can put a PR to add that in.

As for the actual fix, nicely done, and thank you for taking this over.

2024-07-23 22:15 UTC, chmanie reviewed
That's the fix, great work :)

I agree that the lint changes should probably be in a different PR

2024-07-24 09:20 UTC, davecreaser commented
@rdig & @chmanie - thanks for taking a look! Makes total sense about the lint changes, I've removed them from the PR.

2024-07-24 09:37 UTC, chmanie commented on src/routes/graphql/mutations.ts
> +        } = JSON.parse(variables);
I think eventually we should wrap all `JSON.parse` calls in a try-catch. This seems a bit brittle, but also not part of this PR.

2024-07-24 09:40 UTC, chmanie commented on src/routes/graphql/mutations.ts
> +        } = JSON.parse(variables);
Oh wait, apparently we control the serialization for some reason:
https://github.com/JoinColony/colonyCDappAuthProxy/blob/9f6af2f2d41e48b5f2d491309f0202556febe099/src/helpers.ts#L64

2024-07-24 10:20 UTC, rumzledz commented on src/routes/graphql/mutations.ts
> +            data?.from?.toLowerCase() === userAddress?.toLowerCase() // The logged in user is the same as the "from" in the fetched transaction
Not a change request but just thinking out loud, maybe we can write a little util to compare strings by using this method. Something like:
```js
const areStringsEqual = (stringA: string | undefined, stringB: string | undefined) => {
  return stringA?.toLowerCase() === stringB?.toLowerCase();
}

return areStringsEqual(from, userAddress) && areStringsEqual(data?.from, userAddress)
```

I will follow up on the test stuff, just setting up my env!

2024-07-24 10:33 UTC, rumzledz approved these changes
Thanks for the easy to follow steps @davecreaser ✨ I can confirm that I definitely cannot hijack another user's request 🙌 

1. Here's my payload for `CreateTransaction` which is for a MintToken action by Leela
![Screenshot 2024-07-24 at 11 25 11](https://github.com/user-attachments/assets/777a2685-e36c-461f-bff8-35259e8390ac)
2. My GraphQL query response
![Screenshot 2024-07-24 at 11 25 58](https://github.com/user-attachments/assets/9176fa3e-2157-4ff9-b55b-809b26877154)
3. The failing Curl request, using Fry's colony address and Fry's auth cookie value
![Screenshot 2024-07-24 at 11 29 21](https://github.com/user-attachments/assets/2282283c-4da8-417a-8cc3-8264cc75fbc5)

2024-07-24 20:36 UTC, rdig approved these changes
Lint changes gone, so approving. Nicely done!

2024-07-25 22:31 UTC, merged