Add CreatePendingColonyMetadata handler
JoinColony/colonyCDappAuthProxy pull request #8
Opened 2024-01-25 20:25 UTC by ArmandoGraterol

2024-01-31 11:21 UTC, iamsamgibbs approved these changes

2024-01-31 16:08 UTC, jakubcolony requested changes
Hey Armando, nice work! Could you please consider making your util take into account which mutation they're extracting the colony ID from to avoid confusion in future?

2024-01-31 16:08 UTC, jakubcolony commented on src/routes/graphql/utils.ts
> +};
I think this should work on per-mutation basis, potentially with an explanation on why we need to extract it in the first place.
 
Currently if used on something like `ColonyStake` (which id format is `userAddress_colonyAddress`), it would unexpectedly return the `userAddress` instead.

2024-02-14 22:06 UTC, ArmandoGraterol commented
Closing this in favor of https://github.com/JoinColony/colonyCDappAuthProxy/pull/11

2024-02-14 22:06 UTC, closed without merging